name: Test setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

inputs:
  pull_token:
    description: "Token to use for private repo access"
    required: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up git private repo access
        run: |
          git config --global url."https://${{ inputs.pull_token }}@github.com/".insteadOf ssh://git@github.com
          git config --global url."https://${{ inputs.pull_token }}@github.com".insteadOf https://github.com
        shell: bash

      - name: Install Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: "**/go.sum"

      - name: Print Go version
        run: go version
        shell: bash

      - name: Setup GCC
        uses: Dup4/actions-setup-gcc@v1
        with:
          version: latest

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            ~/.rustup/
          key: rust-1.79.0-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: rust-1.79.0-

      - name: Setup Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain 1.79.0 -y
        shell: bash

      - name: Print Rust version
        run: rustc --version
        shell: bash

